masterdata/urls.py
from django.urls import path
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.decorators import login_required

from .views import MasterDataHomeView
from .views import MasterDataCustomerCreateView, MasterDataCustomerListView, MasterDataCustomerUpdateView, MasterDataCustomerDeleteView, import_md_customer_xlsx
from .views import MasterDataProductCreateView, MasterDataProductListView, MasterDataProductUpdateView, MasterDataProductDeleteView, import_md_product_xlsx

urlpatterns = [
    path('', staff_member_required(MasterDataHomeView.as_view(), login_url='login_admin'), name='md_home'),
    path('customer/new/', staff_member_required(MasterDataCustomerCreateView.as_view(), login_url='login_admin'), name='md_customer_input'),
    path('customer/list/', staff_member_required(MasterDataCustomerListView.as_view(), login_url='login_admin'), name='md_customer_list'),
    path('customer/import_xlsx/', staff_member_required(import_md_customer_xlsx, login_url='login_admin'), name='import_md_customer_xlsx'),
    path('customer/<pk>/edit/', staff_member_required(MasterDataCustomerUpdateView.as_view(), login_url='login_admin'), name='md_customer_edit'),
    path('customer/<pk>/delete/', staff_member_required(MasterDataCustomerDeleteView.as_view(), login_url='login_admin'), name='md_customer_delete'),
    path('product/new/',  staff_member_required(MasterDataProductCreateView.as_view(), login_url='login_admin'), name='md_product_input'),
    path('product/list/',  staff_member_required(MasterDataProductListView.as_view(), login_url='login_admin'), name='md_product_list'),
    path('product/import_xlsx/', staff_member_required(import_md_product_xlsx, login_url='login_admin'), name='import_md_product_xlsx'),
    path('product/<pk>/edit/', staff_member_required(MasterDataProductUpdateView.as_view(), login_url='login_admin'), name='md_product_edit'),
    path('product/<pk>/delete/', staff_member_required(MasterDataProductDeleteView.as_view(), login_url='login_admin'), name='md_product_delete'),
]

material_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

urlpatterns = [
    path('for-admin-only/', admin.site.urls),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('account/', include('account.urls')),
    path('account/', include('django.contrib.auth.urls')),
    path('masterdata/', include('masterdata.urls')),
    path('material/', include('material.urls')),
    path('pulling/', include('pulling.urls')),
    path('guest/', include('guest.urls')),
    path('ppic/', include('ppic.urls')),
    path('select2/', include('django_select2.urls')),
]

ppic/urls.py
from django.urls import path
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.decorators import login_required

from .views import PPICHomeView
from .views import ChangeOrderListView, import_change_order_xlsx, delete_co#, ajax_check_co

urlpatterns = [
    path('', PPICHomeView.as_view(), name='ppic_home'),
    path('co/list/', ChangeOrderListView.as_view(), name='change_order_list'),
    path('co/list/import_change_order_xlsx/', import_change_order_xlsx, name='import_change_order_xlsx'),
    path('co/list/delete_co/', delete_co, name='delete_co'),
    #path('co/list/ajax_check/', ajax_check_co, name='check_co')
]

masterdata/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

class MasterDataCustomer(models.Model):
    code = models.CharField(verbose_name='Code', max_length=10, primary_key=True, blank=False, null=False)
    name = models.CharField(verbose_name='Customer', max_length=255, blank=False, null=False)
    address = models.CharField(verbose_name='Address', max_length=255, blank=True, null=False)
    city = models.CharField(verbose_name='City', max_length=25, blank=True, null=True)

    def __str__(self):
        cust = "{0.name}"
        return cust.format(self)

    def get_absolute_url(self):
        return reverse('md_customer_list')

class MasterDataProduct(models.Model):
    part_id_customer = models.CharField(verbose_name='Part ID Customer', max_length=50, blank=False, null=False)
    part_id_internal = models.CharField(verbose_name='Part ID Internal', max_length=25, primary_key=True)
    customer = models.ForeignKey(verbose_name='Customer', to=MasterDataCustomer,on_delete=models.CASCADE)
    part_name = models.CharField(verbose_name='Part Name', max_length=255, blank=False, null=False)
    material = models.CharField(verbose_name='Material', max_length=255, blank=False, null=False)
    
    def __str__(self):
        prod = "{0.part_id_customer}"
        return prod.format(self)
    
    def get_absolute_url(self):
        return reverse('md_product_list')

masterdata/forms.py
from django import forms
from django.forms import ModelForm, SelectDateWidget
from crispy_forms.helper import FormHelper
from crispy_forms.bootstrap import AppendedText
from crispy_forms.layout import Layout, Submit, Row, Column, MultiWidgetField, Reset, Button, Div, HTML
from django.template.defaultfilters import linebreaks_filter
from django.urls import reverse

from material_project import settings

from datetime import datetime, date, time
import pytz
tz = pytz.timezone('Asia/Jakarta')

from .models import MasterDataCustomer, MasterDataProduct

class MasterDataCustomerForm(ModelForm):
    address1 = forms.CharField(max_length=155, required=True)
    address2 = forms.CharField(max_length=100, required=False)
    def __init__(self, *args, **kwargs):
        super(MasterDataCustomerForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.layout = Layout(
            Row(
                Column('code', css_class = 'col-md-2'),
                Column('name', css_class = 'col-md-10'),
                css_class = 'row'
                ),
            Row(
                Column('address1', css_class = 'col-md-12'),
                css_class = 'row'
                ),
            Row(
                Column('address2', css_class = 'col-md-8'),
                Column('city', css_class = 'col-md-4'),
                css_class = 'row'
                ),
            Div(
                Div(Submit('submit', 'Save', css_class = 'btn-primary'), css_class = 'd-inline float-start'),
                Div(
                    Reset('reset', 'Reset', css_class = 'btn-warning'),
                    Button('cancel', 'Back', onclick='history.back()', css_class='btn-danger'),
                    css_class = 'd-inline float-end',   
                    ),
                ),
        )
    class Meta:
        model = MasterDataCustomer
        fields = '__all__'
        exclude = ('address',)

class MasterDataProductForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(MasterDataProductForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.layout = Layout(
            Row(
                Column('part_id_internal', css_class = 'col-md-6'),
                Column('part_id_customer', css_class = 'col-md-6'),
                css_class = 'row'
                ),
            Row(
                Column('customer', css_class = 'col-md-12'),
                css_class = 'row'
                ),
            Row(
                Column('part_name', css_class = 'col-md-12'),
                css_class = 'row'
                ),
            Row(
                Column('material', css_class = 'col-md-12'),
                css_class = 'row'
                ),
            Div(
                Div(Submit('submit', 'Save', css_class = 'btn-primary'), css_class = 'd-inline float-start'),
                Div(
                    Reset('reset', 'Reset', onclick="window.location.reload();", css_class = 'btn-warning'),
                    Button('cancel', 'Back', onclick='history.back()', css_class='btn-danger'),
                    css_class = 'd-inline float-end',   
                    ),
                ),
        )
    class Meta:
        model = MasterDataProduct
        fields = '__all__'

masterdata/views.py
import os, platform

from django.shortcuts import redirect, render
from django.urls import reverse_lazy, reverse
from django.views import View
from django.views.generic import ListView, DetailView, CreateView, TemplateView
from django.views.generic.edit import UpdateView, DeleteView, FormView
from django.db.models import Q, Sum
from django.http import HttpRequest, HttpResponse, Http404, HttpResponseRedirect, JsonResponse, FileResponse
from django.db import IntegrityError
from django.core.files.storage import FileSystemStorage
from django.utils import timezone

import math

from django_tables2 import LazyPaginator, SingleTableView

import xlsxwriter
import openpyxl
import io

from .models import MasterDataCustomer, MasterDataProduct
from .forms import MasterDataCustomerForm, MasterDataProductForm
from .tables import MasterDataCustomerTable, MasterDataProductTable

# Create your views here.

####################################### START HOME #######################################

class MasterDataHomeView(TemplateView):
    template_name = 'masterdata/md_home.html'

####################################### END HOME #######################################

####################################### START CUSTOMER #######################################

class MasterDataCustomerCreateView(CreateView):
    model = MasterDataCustomer
    form_class = MasterDataCustomerForm
    template_name = 'masterdata/md_customer_input.html'

    def form_valid(self, form):
        address1 = form.cleaned_data['address1']
        address2 = form.cleaned_data['address2']
        temp_form = super(MasterDataCustomerCreateView, self).form_valid(form = form)
        form.instance.address = str(address1) + ', ' + str(address2)
        form.save()
        return temp_form

class MasterDataCustomerListView(SingleTableView):
    model = MasterDataCustomer
    template_name = 'masterdata/md_customer_list.html'
    context_table_name = 'md_customer_table'
    table_class = MasterDataCustomerTable

class MasterDataCustomerUpdateView(UpdateView):
    model = MasterDataCustomer
    form_class = MasterDataCustomerForm
    context_object_name = 'masterdata/md_customer_edit'
    template_name = 'masterdata/md_customer_update.html'

    def get_initial(self):
        initial = super().get_initial()
        address = self.object.address
        address_list = address.split(', ')
        index_split = math.ceil(len(address_list)/2)
        if index_split != 1:
            address1_l, address2_l = address_list[0:index_split], address_list[index_split:]
        else:
            address1_l, address2_l = address_list, []
        address1 = ''
        for i in range(0, len(address1_l)):
            if i == len(address1_l)-1:
                address1 = address1 + str(address1_l[i])
            else:
                address1 = address1 + str(address1_l[i]) + ', '
        address2 = ''
        for i in range(0, len(address2_l)):
            if i == len(address2_l)-1:
                address2 = address2 + str(address2_l[i])
            else:
                address2 = address2 + str(address2_l[i]) + ', '

        initial['address1'] = address1
        initial['address2'] = address2
        return initial

    def form_valid(self, form):
        address1 = form.cleaned_data['address1']
        address2 = form.cleaned_data['address2']
        temp_form = super(MasterDataCustomerUpdateView, self).form_valid(form = form)
        form.instance.address = str(address1) + ', ' + str(address2)
        form.save()
        return temp_form

class MasterDataCustomerDeleteView(DeleteView):
    model = MasterDataCustomer
    template_name = 'masterdata/md_customer_delete.html'
    context_object_name = 'md_customer_delete'
    success_url = reverse_lazy('md_customer_list')

def import_md_customer_xlsx(request):
    if request.method == 'POST':
        request_file = request.FILES.get('import_md_customer_xlsx')
        print('request_file = ', request_file)
        if request_file:
            fs = FileSystemStorage()
            file = fs.save(request_file.name, request_file)
            print('file = ', file)
            wb = openpyxl.load_workbook(filename=file, read_only=True)
            ws = wb.active

            customer_list = []
            for row in ws.iter_rows(min_row=2):
                customer = MasterDataCustomer()
                customer.code = row[0].value
                customer.name = row[1].value
                customer.address = row[2].value
                customer.city = row[3].value

                if customer.code != None and customer.name != None:
                    if customer.address == None:
                        customer.address = '-'
                    elif customer.city == None:
                        customer.city = '-'
                    customer_list.append(customer)
        
            try:
                MasterDataCustomer.objects.bulk_create(customer_list)
                wb.close()
                fs.delete(file)

                url = reverse_lazy('md_customer_list')
                warning = 'Success importing new customers from Excel file.'

                response = HttpResponse("<script> alert( '%s' ); window.location='%s' </script>" %(warning, url))
            except IntegrityError as ie:
                wb.close()
                fs.delete(file)
                url = reverse_lazy('md_customer_list')
                print(ie)
                response = HttpResponse("<script> alert( '%s' ); window.location='%s' </script>" %(ie, url))
    return response

####################################### END CUSTOMER #######################################

####################################### START PRODUCT #######################################

class MasterDataProductCreateView(CreateView):
    form_class = MasterDataProductForm
    template_name = 'masterdata/md_product_input.html'

class MasterDataProductListView(SingleTableView):
    model = MasterDataProduct
    template_name = 'masterdata/md_product_list.html'
    context_table_name = 'md_product_table'
    table_class = MasterDataProductTable

    def get_queryset(self):
        query = self.request.GET.get('q')
        if query:
            return MasterDataProduct.objects.filter( Q(part_id_internal__icontains=query) | Q(part_id_customer__icontains=query) | Q(part_name__icontains=query) | Q(material__icontains=query) | Q(customer__name__icontains=query))
        else:
            return MasterDataProduct.objects.all().order_by('customer', 'part_id_internal')

class MasterDataProductUpdateView(UpdateView):
    model = MasterDataProduct
    form_class = MasterDataProductForm
    context_object_name = 'md_product_edit'
    template_name = 'masterdata/md_product_update.html'

class MasterDataProductDeleteView(DeleteView):
    model = MasterDataProduct
    template_name = 'masterdata/md_product_delete.html'
    context_object_name = 'md_product_delete'
    success_url = reverse_lazy('md_product_list')

def import_md_product_xlsx(request):
    if request.method == 'POST':
        request_file = request.FILES.get('import_md_product_xlsx')
        print('request_file = ', request_file)
        if request_file:
            fs = FileSystemStorage()
            file = fs.save(request_file.name, request_file)
            print('file = ', file)
            wb = openpyxl.load_workbook(filename=file, read_only=True)
            ws = wb.active

            product_list = []
            for row in ws.iter_rows(min_row=2):
                product = MasterDataProduct()
                product.part_id_customer = row[0].value
                product.part_id_internal = row[1].value
                customer = row[2].value
                if customer:
                    customer_code = MasterDataCustomer.objects.filter(name = customer).values('code').first()
                    print('customer_code = ', customer_code)
                    if customer_code:
                        product.customer = MasterDataCustomer.objects.get(code = customer_code['code'])
                    else:
                        print('customer_code not on db = ', customer_code)
                        product.customer = MasterDataCustomer.objects.get(code = 'NODATA')
                else:
                    print('customer_id is None from excel = ', customer_code)
                    product.customer = MasterDataCustomer.objects.get(code = 'NODATA')
                product.part_name = row[3].value
                product.material = row[4].value

                if product.part_id_customer != None and product.part_id_internal != None and product.part_name != None and product.material != None:  
                    product_list.append(product)

            try:
                MasterDataProduct.objects.bulk_create(product_list)
                wb.close()
                fs.delete(file)

                url = reverse_lazy('md_product_list')
                warning = 'Success importing new products from Excel file.'

                response = HttpResponse("<script> alert( '%s' ); window.location='%s' </script>" %(warning, url))
            except IntegrityError as ie:
                wb.close()
                fs.delete(file)
                url = reverse_lazy('md_product_list')
                response = HttpResponse("<script> alert( '%s' ); window.location='%s' </script>" %(ie, url))

    return response


####################################### END PRODUCT #######################################

templates/masterdata/md_customer_delete.html
{% extends 'base.html' %} 

{% block title %} Delete Customer {% endblock title %}

{% block header %} Delete Customer {% endblock header %}
{% block content %} 

<div class="container">
    <form action="", method="post">
        {% csrf_token %} 
        <p>Delete the following customer data</p>
        <div class="container">
            <strong><p>Code : {{md_customer_delete.code}}</p></strong>
            <strong><p>Name : {{md_customer_delete.name}}</p></strong>
            <strong><p>Address : {{md_customer_delete.address}}</p></strong>
            <strong><p>City : {{md_customer_delete.city}}</p></strong>
        </div>
        <p>Confirm ?</p>
        <input type="submit" value="Yes" class="btn btn-primary" style="width: 5em;"/>
        <input type="button" value="No" class="btn btn-secondary" onclick="history.back()" style="width: 5em;">
    </form>
</div>
<br>

{% endblock content %}

templates/masterdata/md_customer_input.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %} New Customer Form {% endblock title %}

{% block header %} New Customer Form {% endblock header %}
{% block content %} 
<div class="container">
    {% csrf_token %}
    {% crispy form %}
</div>
<br>
{% endblock content %}

templates/masterdata/md_customer_list.html
{% extends 'base.html' %} 
{% load render_table from django_tables2 %}

{% block title %} Customer List {% endblock title %}

{% block style %} 
<style>
    .md_customer th{
        border: 1px solid white; 
        background-color: rgb(100, 100, 255); 
        border-radius: 5px;
    }
    .md_customer th a {
        font-weight: bold;
        color: white;
        text-decoration: none;
        padding-left: 5px;
        font-size: large;
    }
    .md_customer td{
        border: 1px solid white; 
        background-color: lightblue; 
        border-radius: 5px;
        padding-left: 5px;
        height: 50px;
    }
</style>
{% endblock style %}

{% block header %} Customer List {% endblock header %}

{% block note %}
<hr>
<div class="ms-2 mb-1">
    Please import Excel file (.xlsx) with new customer data following this <a href="https://docs.google.com/spreadsheets/d/1eicj_JVb_BxssIAWQDir4AU0_FSSOJ4r/export?format=xlsx&id=1eicj_JVb_BxssIAWQDir4AU0_FSSOJ4r">template</a>
  </div>
  <br>

  <div>
    <form method="post" action="{% url 'import_md_customer_xlsx' %}" enctype="multipart/form-data">
      <div class="form-group row pb-1">
        {% csrf_token %}
        <div class="form-group col-md-9">
          <label class="ms-2 mb-1" for="import_md_customer_xlsx">Import New Customer (.xlsx)</label>
          <input type="file" accept="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" name="import_md_customer_xlsx" id="import_md_customer_xlsx" class="form-control">
        </div>
        <div class="form-group col-md-3 text-end">
          <label></label>
          <input type="submit" value="Import New Customers (.xlsx)" class="btn btn-success form-control">
        </div>
      </div>  
    </form>
  </div>
{% endblock note %}


{% block content %} 
    {% if md_customer_table %}
        {% render_table md_customer_table %}
    {% endif %}
{% endblock content %}

{% block footer %}
{% endblock footer %}

templates/masterdata/md_customer_update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %} Edit Customer {% endblock title %}

{% block header %} Edit Customer {% endblock header %}
{% block content %} 
<div class="container">
    {% csrf_token %}
    {% crispy form %}
</div>
{% endblock content %}

{% block javascript %} 

{% endblock javascript %}

templates/masterdata/md_home.html
{% extends 'base.html' %} 

{% block title %}Pulling{% endblock title %} 

{% block style %}
{% endblock style %}

{% block header %}Master Data{% endblock header %}

{% block content %} 
{% if user.is_authenticated %}

<div style="display:grid; grid-template-columns:repeat(auto-fit, minmax(250px, 1fr)); padding: 25px">
    {% if user.is_staff %}
    <div style="text-align: center; margin: 15px;">
        <p><a href="{% url 'md_product_input' %}"><i class="fa-solid fa-gear" style="font-size: 200px;"></i></a></p>
        <p><a href="{% url 'md_product_input' %}" style="text-decoration: none;">New Product</a></p>
    </div>

    <div style="text-align: center; margin: 15px;">
        <p><a href="{% url 'md_product_list' %}"><i class="fa-solid fa-gears" style="font-size: 200px;"></i></a></p>
        <p><a href="{% url 'md_product_list' %}" style="text-decoration: none;">Product List</a></p>
    </div>

    <div style="text-align: center; margin: 15px;">
        <p><a href="{% url 'md_customer_input' %}"><i class="fa-solid fa-user-pen" style="font-size: 200px;"></i></a></p>
        <p><a href="{% url 'md_customer_input' %}" style="text-decoration: none;">New Customer</a></p>
    </div>

    <div style="text-align: center; margin: 15px;">
        <p><a href="{% url 'md_customer_list' %}"><i class="fa-solid fa-users" style="font-size: 200px;"></i></a></p>
        <p><a href="{% url 'md_customer_list' %}" style="text-decoration: none;">Customer List</a></p>
    </div>
    {% endif %}
</div>
{% else %} 
<meta http-equiv="refresh" content="0; {% url 'login' %}" />
{% endif %}

{% endblock content %}

templates/masterdata/md_product_delete.html
{% extends 'base.html' %} 

{% block title %} Delete Product - Pulling {% endblock title %}

{% block header %} Delete Product - Pulling {% endblock header %}
{% block content %} 

<div class="container">
    <form action="", method="post">
        {% csrf_token %} 
        <p>Delete the following product data</p>
        <div class="container">
            <strong><p>Part ID Internal : {{md_product_delete.part_id_internal}}</p></strong>
            <strong><p>Part ID Customer : {{md_product_delete.part_id_customer}}</p></strong>
            <strong><p>Customer : {{md_product_delete.customer.name}}</p></strong>
            <strong><p>Part Name : {{md_product_delete.part_name}}</p></strong>
            <strong><p>Material : {{md_product_delete.material}}</p></strong>
            <strong><p>Rack : {{md_product_delete.rack}}</p></strong>
            <strong><p>Bin Quantity : {{md_product_delete.bin_quantity}} pcs</p></strong>
            <strong><p>Packaging Quantity : {{md_product_delete.packaging_quantity}} pcs</p></strong>
            <strong><p>Full Bin Quantity : {{md_product_delete.full_bin_quantity}} pcs</p></strong>
        </div>
        <p>Confirm ?</p>
        <input type="submit" value="Yes" class="btn btn-primary" style="width: 5em;"/>
        <input type="button" value="No" class="btn btn-secondary" onclick="history.back()" style="width: 5em;">
    </form>
</div>
<br>

{% endblock content %}

templates/masterdata/md_product_input.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %} New Product Form {% endblock title %}

{% block header %} New Product Form {% endblock header %}
{% block content %} 
<div class="container">
    {% csrf_token %}
    {% crispy form %}
</div>
<br>
{% endblock content %}

{% block javascript %} 
<script>
    $(document).ready(function()
    {
    // Initialize select2
      var customer_select = new TomSelect("#id_customer",{
        create: false,
        maxItems: 1,
        closeAfterSelect: true,
        placeholder: 'Search, put "NODATA" instead of blank or add the Customer data first.',
      });
      customer_select.clear();
    });
</script>
{% endblock javascript %}

templates/masterdata/md_product_list.html
{% extends 'base.html' %} 
{% load admin_urls %}
{% load render_table from django_tables2 %}

{% block title %} Product List - Pulling {% endblock title %}

{% block style %} 
<style>
  .md_product th{
      border: 1px solid white; 
      background-color: rgb(100, 100, 255); 
      border-radius: 5px;
  }
  .md_product th a {
      font-weight: bold;
      color: white;
      text-decoration: none;
      padding-left: 5px;
      font-size: large;
  }
  .md_product td{
      border: 1px solid white; 
      background-color: lightblue; 
      border-radius: 5px;
      padding-left: 5px;
      height: 50px;
  }
</style>
{% endblock style %}

{% block header %} Product List {% endblock header %}

{% block note %}
<hr>
<div class="ms-2 mb-1">
  Please import Excel file (.xlsx) with new product data following this <a href="https://docs.google.com/spreadsheets/d/1S7k4mhPYBjX54vL9SPzi135gC0uXjrQT/export?format=xlsx&id=1S7k4mhPYBjX54vL9SPzi135gC0uXjrQT">template</a>
</div>
<br>
<div>
  <form method="post" action="{% url 'import_md_product_xlsx' %}" enctype="multipart/form-data">
    <div class="form-group row pb-1">
      {% csrf_token %}
      <div class="form-group col-md-9">
        <label class="ms-2 mb-1" for="import_md_product_xlsx">Import New Products (.xlsx)</label>
        <input type="file" accept="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" name="import_md_product_xlsx" id="import_md_product_xlsx" class="form-control">
      </div>
      <div class="form-group col-md-3 text-end">
        <label></label>
        <input type="submit" value="Import New Products (.xlsx)" class="btn btn-success form-control">
      </div>
    </div>  
  </form>
</div>

{% endblock note %}

{% block content %}
    <div class="mb-4">
      <div class="row">
          <div class="form-group">
              <form class="form-inline" action="{% url 'md_product_list' %}" method="get">
                  <label class="ms-2 mb-1">Search Product</label>
                  <input name="q" class="form-control" type="text" placeholder="Search Product" aria-label="Search Product">
              </form>
          </div>
      </div>
    </div>
    {% if md_product_table %}
        {% render_table md_product_table %}
    {% endif %}
{% endblock content %}

{% block footer %}

  {% if is_paginated %}
    <ul class="pagination align-items-center justify-content-center text-center">

    {% if page_obj.has_previous %}
        <li class="page-item"><a class="page-link" href="?page=1">First</a></li>
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
    {% else %}
        <li class="page-item disabled"><span class="page-link" aria-hidden="true" aria-disabled="true">First</span></li>
        <li class="page-item disabled"><span class="page-link" aria-hidden="true" aria-disabled="true">Previous</span></li>
    {% endif %}
    
    {% if page_obj.number|add:'-4' > 1 %}
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.number|add:'-5' }}">&hellip;</a></li>
    {% endif %}
    
    {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
            <li class="page-item active"><span class="page-link">{{ i }} <span class="sr-only">(current)</span></span></li>
        {% elif i > page_obj.number|add:'-5' and i < page_obj.number|add:'5' %}
            <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
        {% endif %}
    {% endfor %}
    
    {% if page_obj.paginator.num_pages > page_obj.number|add:'4' %}
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.number|add:'5' }}">&hellip;</a></li>
    {% endif %}
    
    {% if page_obj.has_next %}
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-hidden="true">Next</a></li>
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}" aria-hidden="true">Last</a></li>
    {% else %}
        <li class="page-item disabled"><span class="page-link" aria-hidden="true" aria-disabled="true">Next</span></li>
        <li class="page-item disabled"><span class="page-link" aria-hidden="true" aria-disabled="true">Last</span></li>
    {% endif %}
    
    </ul>
  {% endif %}

{% endblock footer %}

templates/masterdata/md_product_update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %} Edit Product - Pulling {% endblock title %}

{% block header %} Edit Product - Pulling {% endblock header %}
{% block content %} 
<div class="container">
    {% csrf_token %}
    {% crispy form %}
</div>
{% endblock content %}

{% block javascript %} 
<script>
    $(document).ready(function()
    {
    // Initialize select2
      new TomSelect("#id_customer",{
        create: false,
        placeholder: 'Search, put "NODATA" instead of blank or add the Customer data first.'
      })
    });
</script>
{% endblock javascript %}