material/urls.py
from django.urls import path
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.decorators import login_required, user_passes_test, permission_required
from django.shortcuts import redirect

from .views import MaterialHomeView
from .views import ProductDeleteView, ProductDetailView, ProductListView, ProductCreateView, ProductUpdateView
from .views import HopperCreateView, HopperListView, HopperUpdateView, HopperDeleteView
from .views import ScrapCreateView, ScrapListView, ScrapUpdateView, ScrapDeleteView
from .views import export_hopper_xlsx, export_material_usage, ajax_fill_hopper_form, import_product_xlsx, export_scrap_xlsx
from .views import MaterialHopperSummary, hopper_line_chart, hopper_bar_chart, hopper_pie_chart

urlpatterns = [
    path('', MaterialHomeView.as_view(), name='material_home'),
    path('product/', ProductListView.as_view(), name='product'),
    path('product/<int:pk>/', ProductDetailView.as_view(), name='product_detail'),
    path('product/new/', staff_member_required(ProductCreateView.as_view(), login_url='login_admin'), name='product_input'),
    path('product/<int:pk>/edit/', staff_member_required(ProductUpdateView.as_view(), login_url='login_admin'), name='product_edit'),
    path('product/<int:pk>/delete/', staff_member_required(ProductDeleteView.as_view(), login_url='login_admin'), name='product_delete'),
    path('product/import_xlsx/', staff_member_required(import_product_xlsx, login_url='login_admin'), name='import_product_xlsx'),
    path('hopper_fill/new/', login_required(HopperCreateView.as_view(), login_url='login'), name='hopper_fill'),
    path('hopper_fill_list/', login_required(HopperListView.as_view(), login_url='login'), name='hopper_fill_data'),
    path('hopper_fill_list/<int:pk>/edit/', login_required(HopperUpdateView.as_view(), login_url='login'), name='hopper_fill_edit'),
    path('hopper_fill_list/<int:pk>/delete/', login_required(HopperDeleteView.as_view(), login_url='login'), name='hopper_fill_delete'),
    path('hopper_fill_list/export_hopper_xlsx/', login_required(export_hopper_xlsx, login_url='login'), name='export_hopper_xlsx'),
    path('hopper_fill_list/export_material_usage/', login_required(export_material_usage, login_url='login'), name='export_material_usage'),
    path('hopper_fill/ajax/hopper/', ajax_fill_hopper_form, name='ajax_fill_hopper_form'),
    path('hopper_fill/summary/', login_required(MaterialHopperSummary.as_view(), login_url='login'), name='hopper_summary'),
    path('hopper_fill/ajax/line_chart/', hopper_line_chart, name='ajax_hopper_line_chart'),
    path('hopper_fill/ajax/bar_chart/', hopper_bar_chart, name='ajax_hopper_bar_chart'),
    path('hopper_fill/ajax/pie_chart/', hopper_pie_chart, name='ajax_hopper_pie_chart'),
    path('scrap_form/new/', login_required(ScrapCreateView.as_view(), login_url='login'), name='scrap_input'),
    path('scrap_list/', login_required(ScrapListView.as_view(), login_url='login'), name='scrap_list'),
    path('scrap_list/<int:pk>/edit/', login_required(ScrapUpdateView.as_view(), login_url='login'), name='scrap_edit'),
    path('scrap_list/<int:pk>/delete/', login_required(ScrapDeleteView.as_view(), login_url='login'), name='scrap_delete'),
    path('scrap_list/export_scrap_xlsx/', login_required(export_scrap_xlsx, login_url='login'), name='export_scrap_xlsx'),
]

material_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

urlpatterns = [
    path('for-admin-only/', admin.site.urls),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('account/', include('account.urls')),
    path('account/', include('django.contrib.auth.urls')),
    path('masterdata/', include('masterdata.urls')),
    path('material/', include('material.urls')),
    path('pulling/', include('pulling.urls')),
    path('guest/', include('guest.urls')),
    path('ppic/', include('ppic.urls')),
    path('select2/', include('django_select2.urls')),
]

ppic/urls.py
from django.urls import path
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.decorators import login_required

from .views import PPICHomeView
from .views import ChangeOrderListView, import_change_order_xlsx, delete_co#, ajax_check_co

urlpatterns = [
    path('', PPICHomeView.as_view(), name='ppic_home'),
    path('co/list/', ChangeOrderListView.as_view(), name='change_order_list'),
    path('co/list/import_change_order_xlsx/', import_change_order_xlsx, name='import_change_order_xlsx'),
    path('co/list/delete_co/', delete_co, name='delete_co'),
    #path('co/list/ajax_check/', ajax_check_co, name='check_co')
]

material/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse

from datetime import datetime, date, time
import pytz

from material_project import settings
from django.contrib.auth import get_user_model as user_model

UserModel = user_model()

# Create your models here.

mesin_choice = []
for a in range(1, 35):
    mesin_choice.append(('A'+str(a), 'A'+str(a)))
for b in range(1, 24):
    mesin_choice.append(('B'+str(b), 'B'+str(b)))
for c in range(1, 44):
    mesin_choice.append(('C'+str(c), 'C'+str(c)))


tz = pytz.timezone('Asia/Jakarta')
date_format = '%d/%m/%Y'
time_format = '%H:%M'
shift1_s = time(8, 0, 0)
shift1_e = time(15, 59, 59)
shift2_s = time(16, 0, 0)
shift2_e = time(23, 59, 59)
shift3_s = time(0, 0, 0)
shift3_e = time(7, 59, 59)
shift_choice = ['Shift 1', 'Shift 2', 'Shift 3']

class Product(models.Model):
    part_id = models.CharField('Part ID', max_length=20, blank=False, null=False)
    part_name = models.CharField('Part Name', max_length=100, blank=False, null=False)
    material = models.CharField('Material', max_length=100, blank=False, null=False)
    cycle_time = models.DecimalField('Cycle Time', max_digits=5, decimal_places=2, blank=False, null=False)
    customer = models.CharField('Customer', max_length=25, blank=False, null=False)
    part_weight = models.DecimalField('Part Weight', max_digits=6, decimal_places=3, blank=False, null=False)
    runner_weight = models.DecimalField('Runner Weight', max_digits=6, decimal_places=3, blank=False, null=False)
    cavity = models.PositiveIntegerField('Cavity', blank=False, null=False)

    def __str__(self):
        p = "{0.part_id} / {0.part_name} / {0.material}"
        return p.format(self)

    def get_absolute_url(self):
        return reverse('product_detail', args=[str(self.id)])


class HopperFillData(models.Model):
    no_mesin = models.CharField('No Mesin', max_length=3, choices=mesin_choice)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='Product')
    no_lot = models.IntegerField('No Lot', blank=True, null=True)
    temp = models.IntegerField('Temperature', blank=False, null=False)
    tanggal = models.DateField('Tanggal', blank=False, null=False)
    jam_isi = models.TimeField('Jam Isi', blank=False, null=False)
    co_virgin = models.PositiveIntegerField('CO Virgin', blank=False, null=False, default=0)
    co_regrind = models.PositiveIntegerField('CO Regrind', blank=False, null=False, default=0)
    pemakaian_virgin = models.PositiveIntegerField('Usage Virgin', blank=False, null=False, default=0)
    pemakaian_regrind = models.PositiveIntegerField('Usage Regrind', blank=False, null=False, default=0)
    kebutuhan_material = models.IntegerField('Kebutuhan Material', blank=True, null=True)
    pic = models.ForeignKey(UserModel, on_delete=models.CASCADE, verbose_name='PIC', to_field='username', blank=True, null=True)
    shift = models.CharField('Shift', max_length=7, blank=True, null=True)
    
    def __str__(self):
        hop = '{0.no_mesin}'
        return hop.format(self)
    
    def get_absolute_url(self):
        return reverse('hopper_fill_data')

    

class Scrap(models.Model):
    tanggal = models.DateField('Tanggal', blank=False, null=False)
    shift = models.CharField('Shift', max_length=7)
    jumlah_purge = models.DecimalField('Purging', decimal_places=2, max_digits=7)
    jumlah_ng = models.DecimalField('Part Scrap', decimal_places=2, max_digits=7)
    jumlah_runner = models.DecimalField('Runner', decimal_places=2, max_digits=7)
    pic = models.ForeignKey(UserModel, on_delete=models.CASCADE, verbose_name='PIC', to_field='username', blank=True, null=True)

    def __str__(self):
        scrap = '{0.tanggal} / {0.shift}'
        return scrap.format(self)
    
    def get_absolute_url(self):
        return reverse('scrap_list')
    
class EstimasiMaterialUsageCO(models.Model):
    tanggal_co = models.DateField('Tanggal Co', blank=True, null=True)
    tanggal_operasi = models.DateField('Tanggal',blank=True, null=True)
    part_no = models.CharField('Part No', max_length=255, blank=True, null=True)
    target_output = models.PositiveIntegerField('Target Output', blank=True, null=True)
    total_berat_material = models.DecimalField('Total Berat Material', max_digits=200, decimal_places=2, blank=True, null=True)
    virgin_per_day = models.DecimalField('Virgin / Day', max_digits=200, decimal_places=2, blank=True, null=True)
    regrind_per_day = models.DecimalField('Regrind / Day', max_digits=200, decimal_places=2, blank=True, null=True)

    def __str__(self):
        emu = '{0.tanggal_operasi} / {0.virgin_per_day} / {0.regrind_per_day}'
        return emu.format(self)

material/forms.py
from django import forms
from django.forms import ModelForm, SelectDateWidget
from crispy_forms.helper import FormHelper
from crispy_forms.bootstrap import AppendedText
from crispy_forms.layout import Layout, Submit, Row, Column, MultiWidgetField
from django.core.exceptions import ValidationError

from material_project import settings

from datetime import datetime, date, time
import pytz
tz = pytz.timezone('Asia/Jakarta')


from django_select2.forms import Select2Widget, ModelSelect2Widget

from .models import HopperFillData, Product, Scrap

class ProductForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(ProductForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.layout = Layout(
            Row(
                Column('part_id', css_class = 'col-md-4'),
                Column('part_name', css_class = 'col-md-8'),
                css_class = 'row'
                ),
            Row(
                Column('material', css_class = 'col-md-10'),
                Column(AppendedText('cycle_time', 'sec'), css_class = 'col-md-2'),
                css_class = 'row'
                ),
            Row(
                Column('customer', css_class = 'col-md-6'),
                Column(AppendedText('part_weight', 'gr'), css_class = 'col-md-2'),
                Column(AppendedText('runner_weight', 'gr'), css_class = 'col-md-2'),
                Column('cavity', css_class = 'col-md-2'),
                css_class = 'row'
                ),
            Submit('submit_product', 'Save Product')
        )
    
    class Meta:
        model = Product
        fields = '__all__'

class HopperForm(ModelForm):
    total_co = forms.IntegerField(label='Total CO', required=False)
    def __init__(self, *args, **kwargs):
        super(HopperForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.layout = Layout(
            Row(
                Column('no_mesin', css_class = 'col-md-2'),
                Column('product', css_class = 'col-md-7'),
                Column('no_lot', css_class = 'col-md-1'),
                Column(AppendedText('temp', '°C'), css_class = 'col-md-2'),
                css_class = 'row'
            ),
            Row(
                Column(MultiWidgetField('tanggal', attrs = ({'style':'width : 30%; display : inline-block; margin-right : 0.15em'})), css_class = 'col-md-8'),
                Column('jam_isi', css_class = 'col-md-4'),
                css_class = 'row'
            ),
            Row(
                Column(AppendedText('co_virgin', 'kg'), css_class = 'col-md-3'),
                Column(AppendedText('co_regrind', 'kg'), css_class = 'col-md-3'),
                Column(AppendedText('pemakaian_virgin', 'kg'), css_class = 'col-md-3'),
                Column(AppendedText('pemakaian_regrind', 'kg'), css_class = 'col-md-3'),
                css_class = 'row'
            ),
            Row(
                Column(AppendedText('total_co', 'kg'), css_class = 'col-md-6'),
                Column(AppendedText('kebutuhan_material', 'kg'), css_class = 'col-md-6'),
            ),
            Submit('submit_material_hopper', 'Submit Material Hopper')
        )

        self.fields['no_mesin'].initial = 'A1'
        self.fields['tanggal'].widget = SelectDateWidget(years= range(2000, datetime.today().year + 3))
        self.fields['tanggal'].initial = date.today()
        self.fields['jam_isi'].widget = forms.TimeInput(attrs={'type':'time'})
        self.fields['jam_isi'].initial = datetime.now().astimezone(tz=tz).strftime('%H:%M')
        self.fields['shift'].widget = forms.HiddenInput()
        self.fields['shift'].initial = 'Shift 1'
        self.fields['pic'].widget = forms.HiddenInput()
        self.fields['pic'].initial = None
        self.fields['total_co'].widget.attrs['readonly'] = True
        self.fields['total_co'].initial = 0
        self.fields['kebutuhan_material'].widget.attrs['readonly'] = True
        print(self.errors)
    
    class Meta:
        model = HopperFillData
        fields = '__all__'

class ScrapForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(ScrapForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.layout = Layout(
            Row(
                MultiWidgetField('tanggal', attrs = ({'style':'width : 32.5%; display: inline-block; margin-right:0.15em'},)),
                css_class = 'row'
                ),
            Row(
                Column('shift', css_class='col-md-4'), 
                css_class = 'row'),
            Row(
                Column(AppendedText('jumlah_purge', 'kg'), css_class='col-md-4'),
                Column(AppendedText('jumlah_ng', 'kg'), css_class='col-md-4'),
                Column(AppendedText('jumlah_runner', 'kg'), css_class='col-md-4'),
                css_class = 'row'
            ),
            Submit('submit_scrap', 'Submit Scrap')
        )

        self.fields['tanggal'].widget = SelectDateWidget(years = range(2000, date.today().year+3))
        self.fields['tanggal'].initial = datetime.today()
        shift_choices = (('Shift 1', 'Shift 1'), ('Shift 2', 'Shift 2'), ('Shift 3', 'Shift 3'),)
        self.fields['shift'] = forms.ChoiceField(choices=shift_choices)
        self.fields['shift'].initial = self.get_shift()
        self.fields['pic'].widget = forms.HiddenInput()
        self.fields['pic'].initial = None
        self.fields['jumlah_purge'].initial = 0.00
        self.fields['jumlah_ng'].initial = 0.00
        self.fields['jumlah_runner'].initial = 0.00

        
    def get_shift(self):
        tz = pytz.timezone('Asia/Jakarta')
        get_time_str = datetime.now(tz = tz).strftime('%H:%M')
        get_time_h = get_time_str[:2]
        get_time_m = get_time_str[3:5]

        get_time = time(int(get_time_h), int(get_time_m), 0)
        shift1_s = time(8, 0, 0)
        shift1_e = time(15, 59, 59)
        shift2_s = time(16, 0, 0)
        shift2_e = time(23, 59, 59)
        shift3_s = time(0, 0, 0)
        shift3_e = time(7, 59, 59)

        if get_time >= shift1_s and get_time <= shift1_e:
            return 'Shift 1'
        elif get_time >= shift2_s and get_time <= shift2_e:
            return 'Shift 2'
        else:
            return 'Shift 3'
    
    class Meta:
        model = Scrap
        fields = '__all__'
        labels = {  'tanggal' : ('Tanggal'),
                    'shift' : ('Shift'),
                    'jumlah_purge' : ('Purging'),
                    'jumlah_ng' : ('Part Scrap'),
                    'jumlah_runner' : ('Runner'),
        }
        field_order = ['tanggal', 'shift', 'jumlah_purge', 'jumlah_ng', 'jumlah_runner',]

templates/material/hopper_fill_edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %} Edit Material Hopper Data {% endblock title %}
{% block header %} Edit Material Hopper Data {% endblock header %}
{% block content %}
    <style>
        form label{
            display: block;
        }
    </style>
    

    <div>
        {% csrf_token %} 
        {% crispy form %}
    </div>
    
    {% endblock content %}

templates/material/material_home.html
{% extends 'base.html' %} 

{% block header %}Material{% endblock header %}

{% block content %} 
{% if user.is_authenticated %}

<div style="display:grid; grid-template-columns:repeat(auto-fit, minmax(250px, 1fr)); padding: 25px">
    {% if user.is_staff %}
    <div style="text-align: center; margin: 15px;">
        <p><a href="{% url 'product_input' %}"><i class="fa-solid fa-gear" style="font-size: 200px;"></i></a></p>
        <p><a href="{% url 'product_input' %}" style="text-decoration: none;">Product Form</a></p>
    </div>

    <div style="text-align: center; margin: 15px;">
        <p><a href="{% url 'product' %}"><i class="fa-solid fa-gears" style="font-size: 200px;"></i></a></p>
        <p><a href="{% url 'product' %}" style="text-decoration: none;">Product List</a></p>
    </div>
    {% endif %}
    <div style="text-align: center; margin: 15px;">
        <p><a href="{% url 'hopper_fill' %}"><i class="fa-solid fa-file-pen" style="font-size: 200px;"></i></a></p>
        <p><a href="{% url 'hopper_fill' %}" style="text-decoration: none;">Material Hopper Form</a></p>
    </div>

    <div style="text-align: center; margin: 15px;">
        <p><a href="{% url 'hopper_fill_data' %}"><i class="fa-solid fa-clipboard-list" style="font-size: 200px;"></i></a></p>
        <p><a href="{% url 'hopper_fill_data' %}" style="text-decoration: none;">Material Hopper List</i></a></p>
    </div>

    <div style="text-align: center; margin: 15px;">
        <p><a href="{% url 'hopper_summary' %}"><i class="fa-solid fa-chart-line" style="font-size: 200px;"></i></a></p>
        <p><a href="{% url 'hopper_summary' %}" style="text-decoration: none;">Material Hopper Summary</i></a></p>
    </div>

    <div style="text-align: center; margin: 15px;">
        <p><a href="{% url 'scrap_input' %}"><i class="fa-solid fa-recycle" style="font-size: 200px;"></i></a></p>
        <p><a href="{% url 'scrap_input' %}" style="text-decoration: none;">Scrap Form</i></a></p>
    </div>

    <div style="text-align: center; margin: 15px;">
        <p><a href="{% url 'scrap_list' %}"><i class="fa-regular fa-clipboard" style="font-size: 200px;"></i></a></p>
        <p><a href="{% url 'scrap_list' %}" style="text-decoration: none;">Scrap List</i></a></p>
    </div>
</div>
{% else %} 
<meta http-equiv="refresh" content="0; {% url 'login' %}" />
{% endif %}

{% endblock content %}

templates/material/product.html
{% extends 'base.html' %} 
{% load admin_urls %}

{% block title %} Product List {% endblock title %}
{% block header %} Product List {% endblock header %}

{% block note %}
<hr>
<div>
  Please import Excel file (.xlsx) with new product data following this <a href="https://drive.google.com/uc?export=download&id=1wh3Pg1EJSYvahboGGKTlVcERraqAo8-i">template</a>
</div>
<br>
<div>
  <form method="post" action="{% url 'import_product_xlsx' %}" enctype="multipart/form-data">
    <div class="form-group row pb-1">
      {% csrf_token %}
      <div class="form-group col-md-9">
        <label for="import_product_xlsx">New Product Excel</label>
        <input type="file" accept="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" name="import_product_xlsx" id="import_product_xlsx" class="form-control">
      </div>
      <div class="form-group col-md-3 text-end">
        <label></label>
        <input type="submit" value="Import Product Excel" class="btn btn-success form-control">
      </div>
    </div>  
  </form>
</div>
{% endblock note %}

{% block content %} 

<div class="mb-4">
    <div class="row">
        <div class="form-group name1 col-md-10 text-start">
            <form class="form-inline mt-2 mt-md-0" action="{% url 'product' %}" method="get" style="text-align:left; width: 25em;">
                <input name="q" class="form-control mr-sm-2" type="text" placeholder="Search Product" aria-label="Search Product">
            </form>
        </div>
        <div class="form-group name2 col-md-2 text-end">
            <button class="btn btn-primary"><a href="{% url 'product_input'%}" style="color: white; text-decoration: none;">Add New Product</a></button>
        </div>
    </div>
</div>

<div>
    <table style="border: 1px solid white; width: 100%;">
        <tr style="border: 1px solid white;">
            <th style="width: 3%; border: 1px solid white; background-color: rgb(100, 100, 255); color: white; text-align: center;">#</th>
            <th style="width: 20%; border: 1px solid white; background-color: rgb(100, 100, 255); color: white;">Part ID</th>
            <th style="width: 32%; border: 1px solid white; background-color: rgb(100, 100, 255); color: white">Part Name</th>
            <th style="width: 35%; border: 1px solid white; background-color: rgb(100, 100, 255); color: white">Material</th>
            <th style="width: 10%; border: 1px solid white; background-color: rgb(100, 100, 255); color: white; text-align: center;" colspan="2"></th>
        </tr>
        {% for product in product_list %} 
        <tr style="border: 1px solid white;">
            <td style="width: 3%;  border: 1px solid white; background-color: lightblue; text-align: center;">{{ page_obj.start_index|add:forloop.counter0 }}</td>
            <td style="width: 20%; border: 1px solid white; background-color: lightblue;"><a href="{% url 'product_detail' product.pk %}">{{product.part_id}}</td>
            <td style="width: 32%; border: 1px solid white; background-color: lightblue;">{{product.part_name}}</td>
            <td style="width: 35%; border: 1px solid white; background-color: lightblue;">{{product.material}}</td>
            <td style="width: 5%;  border: 1px solid white; border-right: 0px; background-color: lightblue; text-align: center;"><a href="{% url 'product_edit' product.pk %}"><i class="fa-solid fa-pen"></i></a></td>
            <td style="width: 5%;  border: 1px solid white; border-left: 0px; background-color: lightblue; text-align: center;"><a href="{% url 'product_delete' product.pk %}"><i class="fa-solid fa-trash-can"></i></a></td>
        </tr>
        {% endfor %}
    </table>
</div>

{% endblock content %}

{% block footer %}

  {% if is_paginated %}
    <ul class="pagination align-items-center justify-content-center text-center">

    {% if page_obj.has_previous %}
        <li class="page-item"><a class="page-link" href="?page=1">First</a></li>
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
    {% else %}
        <li class="page-item disabled"><span class="page-link" aria-hidden="true" aria-disabled="true">First</span></li>
        <li class="page-item disabled"><span class="page-link" aria-hidden="true" aria-disabled="true">Previous</span></li>
    {% endif %}
    
    {% if page_obj.number|add:'-4' > 1 %}
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.number|add:'-5' }}">&hellip;</a></li>
    {% endif %}
    
    {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
            <li class="page-item active"><span class="page-link">{{ i }} <span class="sr-only">(current)</span></span></li>
        {% elif i > page_obj.number|add:'-5' and i < page_obj.number|add:'5' %}
            <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
        {% endif %}
    {% endfor %}
    
    {% if page_obj.paginator.num_pages > page_obj.number|add:'4' %}
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.number|add:'5' }}">&hellip;</a></li>
    {% endif %}
    
    {% if page_obj.has_next %}
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-hidden="true">Next</a></li>
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}" aria-hidden="true">Last</a></li>
    {% else %}
        <li class="page-item disabled"><span class="page-link" aria-hidden="true" aria-disabled="true">Next</span></li>
        <li class="page-item disabled"><span class="page-link" aria-hidden="true" aria-disabled="true">Last</span></li>
    {% endif %}
    
    </ul>
  {% endif %}

{% endblock footer %}

templates/material/product_delete.html
{% extends 'base.html' %} 

{% block title %} Delete Product {% endblock title %}

{% block header %} Delete Product {% endblock header %}
{% block content %} 

<div class="container">
    <form action="", method="post">
        {% csrf_token %} 
        <p>Delete the following product data</p>
        <div class="container">
            <strong><p>Part ID : {{product_delete.part_id}}</p></strong>
            <strong><p>Part Name : {{product_delete.part_name}}</p></strong>
            <strong><p>Material : {{product_delete.material}}</p></strong>
            <strong><p>Cycle Time : {{product_delete.cycle_time}}</p></strong>
            <strong><p>Customer : {{product_delete.customer}}</p></strong>
            <strong><p>Part Weight : {{product_delete.part_weight}}</p></strong>
            <strong><p>Runner Weight : {{product_delete.runner_weight}}</p></strong>
            <strong><p>Cavity : {{product_delete.cavity}}</p></strong>
        </div>
        <p>Confirm ?</p>
        <input type="submit" value="Yes" class="btn btn-primary" style="width: 5em;"/>
        <input type="button" value="No" class="btn btn-secondary" onclick="history.back()" style="width: 5em;">
    </form>
</div>
<br>

{% endblock content %}

templates/material/product_edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %} Edit Product {% endblock title %}

{% block header %} Edit Product {% endblock header %}
{% block content %} 
<div class="container">
    {% csrf_token %}
    {% crispy form %}
</div>
{% endblock content %}

templates/material/product_input.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %} Product Form {% endblock title %}

{% block header %} Product Form {% endblock header %}
{% block content %} 
<div class="container">
    {% csrf_token %}
    {% crispy form %}
</div>
<br>
{% endblock content %}

templates/material/scrap_delete.html
{% extends 'base.html' %} 

{% block title %} Delete Scrap {% endblock title %}

{% block header %} Delete Scrap {% endblock header %}
{% block content %} 

<div class="container">
    <form action="", method="post">
        {% csrf_token %} 
        <p>Delete the following scrap data</p>
        <div class="container">
            <strong><p>Tanggal : {{scrap_delete.tanggal|date:"d-M-Y"}}</p></strong>
            <strong><p>Shift : {{scrap_delete.shift}}</p></strong>
            <strong><p>Purging : {{scrap_delete.jumlah_purge}}</p></strong>
            <strong><p>Part Scrap : {{scrap_delete.jumlah_ng}}</p></strong>
            <strong><p>Runner : {{scrap_delete.jumlah_runner}}</p></strong>
            <strong><p>PIC : {{scrap_delete.pic}}</p></strong>
        </div>
        <p>Confirm ?</p>
        <input type="submit" value="Yes" class="btn btn-primary" style="width: 5em;"/>
        <input type="button" value="No" class="btn btn-secondary" onclick="history.back()" style="width: 5em;">
    </form>
</div>
<br>

{% endblock content %}